<a href="https://colab.research.google.com/github/Taehwi11/Q1_2022/blob/python/12_01_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_iris
import pandas as pd
IRIS_Dataset=load_iris()
X_DataFrame=pd.DataFrame(data=IRIS_Dataset.data,columns=IRIS_Dataset.feature_names)
Y_DataFrame=pd.DataFrame(data=IRIS_Dataset.target,columns=['Species'])
IRIS_DataFrame=pd.concat([X_DataFrame,Y_DataFrame],axis=1)
IRIS_DataFrame.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
from sklearn.preprocessing import MinMaxScaler
Scaler_IRIS=MinMaxScaler().fit(X_DataFrame)
pd.DataFrame(Scaler_IRIS.transform(X_DataFrame),columns=IRIS_Dataset.feature_names)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit
Split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=0)
for Train_index, Test_index in Split.split(IRIS_DataFrame,IRIS_DataFrame['Species']):
  Train_IRIS=IRIS_DataFrame.loc[Train_index]
  Test_IRIS=IRIS_DataFrame.loc[Test_index]
  Train_IRIS_X,Train_IRIS_Y=Train_IRIS.iloc[:,:4],Train_IRIS['Species']
  Test_IRIS_X,Test_IRIS_Y=Test_IRIS.iloc[:,:4],Test_IRIS['Species']

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

Scaler_IRIS=MinMaxScaler()
KNN_CLF=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=2,weights='uniform')
Full_pipeline_KNN=Pipeline(steps=[('scaler',Scaler_IRIS),('Classifier',KNN_CLF)])
Full_pipeline_KNN.fit(Train_IRIS_X,Train_IRIS_Y)
Test_IRIS_Pred=Full_pipeline_KNN.predict(Test_IRIS_X)
pd.DataFrame(confusion_matrix(Test_IRIS_Y,Test_IRIS_Pred))
print("Accuracy=",Full_pipeline_KNN.score(Test_IRIS_X,Test_IRIS_Y))

Accuracy= 0.9666666666666667